name: Branch-Based Deployment with Semantic Versioning

# Trigger conditions for the workflow
on:
  push:
    branches:
      - dev
      - main
      - sandbox
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Semantic version tags
  pull_request:
    branches:
      - dev

# Global environment variables
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: shambhuc45/cicd-nextapp

jobs:
  # ==============================================
  # Version Check Job - Determines version number
  # ==============================================
  version-check:
    runs-on: ubuntu-latest
    outputs:
      should_version: ${{ steps.check.outputs.should_version }}
      version: ${{ steps.version.outputs.version }}
    steps:
      # Checkout code with full history for version analysis
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check version condition
        id: check
        run: |
          # Only generate version for 'main' branch or version tags
          if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == refs/tags/* ]]; then
            echo "should_version=true" >> $GITHUB_OUTPUT
          else
            echo "should_version=false" >> $GITHUB_OUTPUT
          fi

      # Generate semantic version based on commit messages
      - name: Generate Semantic Version
        id: version
        if: steps.check.outputs.should_version == 'true'
        uses: paulhatch/semantic-version@v3
        with:
          major_pattern: "BREAKING CHANGE"
          minor_pattern: "feat"
          patch_pattern: "fix"
          format: "{major}.{minor}.{patch}"

  # ==============================================
  # Build Job - Builds and tags Docker image
  # ==============================================
  build:
    needs: version-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GH_NEW_PAT }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          # Determine tag name based on branch
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            IMAGE_TAG="dev-$(git rev-parse --short HEAD)"
          elif [[ "${{ needs.version-check.outputs.should_version }}" == "true" ]]; then
            IMAGE_TAG="${{ needs.version-check.outputs.version }}"
          else
            IMAGE_TAG="${{ github.ref_name }}-$(git rev-parse --short HEAD)"
          fi

          FULL_TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG
          echo "FULL_TAG=$FULL_TAG" >> $GITHUB_ENV

          docker build -t $FULL_TAG .
          docker push $FULL_TAG

          # Tag latest for main branch
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            LATEST_TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            docker tag $FULL_TAG $LATEST_TAG
            docker push $LATEST_TAG
          fi

      - name: Create Git Tag
        if: needs.version-check.outputs.should_version == 'true' && github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${{ needs.version-check.outputs.version }}
          git push origin v${{ needs.version-check.outputs.version }}

      - name: Logout from Container Registry
        if: always()
        run: docker logout ${{ env.REGISTRY }}

  # ==============================================
  # Deploy Job - Deploys to appropriate environment
  # ==============================================
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/sandbox') && github.event_name != 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine Environment
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "ENV=development" >> $GITHUB_ENV
            echo "PORT=3001" >> $GITHUB_ENV
            echo "DOMAIN=test.hatesglobal.com" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENV=production" >> $GITHUB_ENV
            echo "PORT=3000" >> $GITHUB_ENV
            echo "DOMAIN=hatesglobal.com" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/sandbox" ]]; then
            echo "ENV=sandbox" >> $GITHUB_ENV
            echo "PORT=3002" >> $GITHUB_ENV
            echo "DOMAIN=sandbox.hatesglobal.com" >> $GITHUB_ENV
          fi

          echo "IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying ${{ env.IMAGE_NAME }} to ${{ env.ENV }} (${{ env.DOMAIN }})"

            mkdir -p ~/deployments/${{ env.IMAGE_NAME }} && cd ~/deployments/${{ env.IMAGE_NAME }}

            # Create Docker Compose file
            cat << 'EOF' > docker-compose.yml
            version: '3.8'
            services:
              app:
                image: ${IMAGE_NAME}
                ports:
                  - "${PORT}:3000"
                environment:
                  - NODE_ENV=${ENV}
                  - DOMAIN=${DOMAIN}
                restart: unless-stopped
            EOF

            echo "PORT=${{ env.PORT }}" > .env
            echo "NODE_ENV=${{ env.ENV }}" >> .env
            echo "DOMAIN=${{ env.DOMAIN }}" >> .env
            echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" >> .env

            sudo docker compose down || true
            sudo docker image prune -af

            sudo docker compose --env-file .env up -d

            echo "Successfully deployed to ${{ env.DOMAIN }}"
